version: "3.8"

services:
  jobmanager:
    build:
      context: .
    ports:
      - 6123:6123
      - 8081:8081
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    build:
      context: .
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    depends_on:
      - jobmanager
    deploy:
      replicas: 3
    